import org.foobar.library.model.Metric;
import com.example.droolsprototype.execution.ExecutionService;
import com.example.droolsprototype.DroolsPrototypeApplication;
import java.lang.Double;
import java.lang.System;


rule "trigger_pod_CPU_request"
    dialect "mvel"
    when
        metric : Metric(
            name == "request_duration_seconds_sum" &&
            valueDouble > DroolsPrototypeApplication.CPU_THRESHOLD
        )
        executor : ExecutionService()
    then
        System.out.println("CPU usage too high!");
        executor.reduceCPU();
end