---
apiVersion: v1
kind: Service
metadata:
  name: drools-engine
  namespace: drools-demo
spec:
  selector:
    app: drools-engine
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080


